#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/krails/krails_config"

lib_path = File.expand_path("../lib", __dir__)
$:.unshift(lib_path) unless $:.include?(lib_path)
require "krails/cli"

Signal.trap("INT") do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Krails::CLI.start
rescue Krails::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
